### ISSUE TITLE
Add link to the GitHub repository behind the page

### ISSUE THREAD

**Issue by dellagustin-sap** [mrsanz/jekyll-roles-theme#28]
This will enable users to easily find how to contribute to the page.

It could possibly be done with https://jekyll.github.io/github-metadata/site.github/ using site.github.repository_url and other similar fields.

**Comment by dellagustin-sap** [comment]
tested with adding this to `_includes/navigation.html`:

```html
    {% if site.github != nil %}
    <li class="nav-item">
      <a href="{{ site.github.repository_url }}" class="nav-item nav-link text-light active"><i class="fab fa-github"></i> {{ site.github.repository_nwo }}</a>
    </li>
    {% endif %}
```

and this to `_config.yml`, to simulate the necessary fields from https://jekyll.github.io/github-metadata/site.github/ when running locally:
```yml
# Uncomment the lines below for local testing of https://jekyll.github.io/github-metadata/site.github/
github:
  repository_url: https://github.com/InnerSourceCommons/working-group-roles
  repository_nwo: InnerSourceCommons/working-group-roles
```

Result (focus on the header):
<img width="1189" alt="image" src="https://github.com/mrsanz/jekyll-roles-theme/assets/54676965/1fb95f27-eac4-405d-b9c2-a0d8d0d0367e">

How it currently is, for comparison (+ `backlink: InnerSource Commons, https://innersourcecommons.org/community/` at `_config.yml` on the screenshot above):

<img width="1213" alt="image" src="https://github.com/mrsanz/jekyll-roles-theme/assets/54676965/5011ce29-bb8c-4453-83f0-0e22c3327e1c">

@rrrutledge , I could apply this to our fork at https://github.com/InnerSourceCommons/working-group-roles, if it is not included upstream.

Note: The change as described in this comment is not backwards compatible, the feature is turned on by default.
